site_name: pytest-locker
site_url: https://pytest-locker.daanluttik.nl/
theme:
  name: material
  icon:
    repo: fontawesome/brands/github
  font:
    text: inter
    code: JetBrains+Mono
  favicon: assets/images/favicon.png
  logo: assets/images/logo-shape-white.svg
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  custom_dir: docs/overrides
  features:
    - header.autohide

extra_css:
  - stylesheets/extra-style.css

markdown_extensions:
  - meta
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - pymdownx.superfences
  - toc:
      permalink: true


repo_name: luttik/pytest-locker
repo_url: https://github.com/luttik/pytest-locker
edit_uri: edit/main/docs/
