# This workflow will install Python dependencies, run test and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: CodeCov

on: push

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
        architecture: x64
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry config virtualenvs.create false
        poetry install
    - name: upload codecov data
      run: |
        pytest --cov --cov-fail-under=0 --cov-report xml
        codecov
      env:
        CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
